"""Loot, predicate, advancement and recipe type ids by version, for the
problems list. GENERATED from the Spyglass registries (via the minecode MCP
server) for the first release of every pack format from 1.16.1 to 26.3 — do
not edit by hand.

``NAMES[registry][id] = (since, until)``: the first release that has the id
(``None``: every release in the table) and the first that no longer has it
(``None``: still there). ``COVERED_SINCE[registry]`` is the first release the
table knows the registry for; older versions are not checked.
"""

from __future__ import annotations

COVERED_SINCE: dict[str, str] = {
    "loot_condition_type": "1.16.1",
    "loot_function_type": "1.16.1",
    "loot_pool_entry_type": "1.16.1",
    "recipe_serializer": "1.16.1",
    "trigger_type": "1.20.3",
}

NAMES: dict[str, dict[str, tuple[str | None, str | None]]] = {
    "loot_condition_type": {
        "all_of": ("1.20", None),
        "alternative": (None, "1.20"),
        "any_of": ("1.20", None),
        "block_state_property": (None, "26.3"),
        "damage_source_properties": (None, None),
        "enchantment_active_check": ("1.21", None),
        "entity_properties": (None, None),
        "entity_scores": (None, None),
        "environment_attribute_check": ("26.1", None),
        "float_value_check": ("26.3", None),
        "int_value_check": ("26.3", None),
        "inverted": (None, None),
        "killed_by_player": (None, None),
        "location_check": (None, None),
        "match_block": ("26.3", None),
        "match_tool": (None, None),
        "random_chance": (None, None),
        "random_chance_with_enchanted_bonus": ("1.21", None),
        "random_chance_with_looting": (None, "1.21"),
        "reference": (None, "26.3"),
        "survives_explosion": (None, None),
        "table_bonus": (None, None),
        "time_check": (None, None),
        "value_check": ("1.17", "26.3"),
        "weather_check": (None, None),
    },
    "loot_function_type": {
        "apply_bonus": (None, None),
        "copy_components": ("1.20.5", None),
        "copy_custom_data": ("1.20.5", None),
        "copy_name": (None, None),
        "copy_nbt": (None, "1.20.5"),
        "copy_state": (None, None),
        "discard": ("1.21.11", None),
        "enchant_randomly": (None, None),
        "enchant_with_levels": (None, None),
        "enchanted_count_increase": ("1.21", None),
        "exploration_map": (None, None),
        "explosion_decay": (None, None),
        "fill_player_head": (None, None),
        "filtered": ("1.20.5", None),
        "furnace_smelt": (None, None),
        "limit_count": (None, None),
        "looting_enchant": (None, "1.21"),
        "modify_contents": ("1.20.5", None),
        "reference": ("1.20", "26.3"),
        "sequence": ("1.20.2", None),
        "set_attributes": (None, None),
        "set_banner_pattern": ("1.17", None),
        "set_book_cover": ("1.20.5", None),
        "set_components": ("1.20.5", None),
        "set_contents": (None, None),
        "set_count": (None, None),
        "set_custom_data": ("1.20.5", None),
        "set_custom_model_data": ("1.20.5", None),
        "set_damage": (None, None),
        "set_enchantments": ("1.17", None),
        "set_firework_explosion": ("1.20.5", None),
        "set_fireworks": ("1.20.5", None),
        "set_instrument": ("1.19", None),
        "set_item": ("1.20.5", None),
        "set_loot_table": (None, None),
        "set_lore": (None, None),
        "set_name": (None, None),
        "set_nbt": (None, "1.20.5"),
        "set_ominous_bottle_amplifier": ("1.20.5", None),
        "set_potion": ("1.18", None),
        "set_random_dyes": ("26.1", None),
        "set_random_potion": ("26.1", None),
        "set_stew_effect": (None, None),
        "set_writable_book_pages": ("1.20.5", None),
        "set_written_book_pages": ("1.20.5", None),
        "toggle_tooltips": ("1.20.5", None),
    },
    "loot_pool_entry_type": {
        "alternatives": (None, None),
        "dynamic": (None, None),
        "empty": (None, None),
        "group": (None, None),
        "item": (None, None),
        "loot_table": (None, None),
        "sequence": (None, None),
        "slots": ("1.21.11", None),
        "tag": (None, None),
    },
    "recipe_serializer": {
        "blasting": (None, None),
        "brewing": ("26.3", None),
        "campfire_cooking": (None, None),
        "crafting_decorated_pot": ("1.19.4", None),
        "crafting_dye": ("26.1", None),
        "crafting_imbue": ("26.1", None),
        "crafting_shaped": (None, None),
        "crafting_shapeless": (None, None),
        "crafting_special_armordye": (None, "26.1"),
        "crafting_special_bannerduplicate": (None, None),
        "crafting_special_bookcloning": (None, None),
        "crafting_special_firework_rocket": (None, None),
        "crafting_special_firework_star": (None, None),
        "crafting_special_firework_star_fade": (None, None),
        "crafting_special_mapcloning": (None, "26.1"),
        "crafting_special_mapextending": (None, None),
        "crafting_special_repairitem": (None, None),
        "crafting_special_shielddecoration": (None, None),
        "crafting_special_shulkerboxcoloring": (None, "1.21.2"),
        "crafting_special_suspiciousstew": (None, "1.21.2"),
        "crafting_special_tippedarrow": (None, "26.1"),
        "crafting_transmute": ("1.21.2", None),
        "smelting": (None, None),
        "smithing": (None, "1.20"),
        "smithing_transform": ("1.19.4", None),
        "smithing_trim": ("1.19.4", None),
        "smoking": (None, None),
        "stonecutting": (None, None),
    },
    "trigger_type": {
        "allay_drop_item_on_block": (None, None),
        "any_block_use": ("1.20.5", None),
        "avoid_vibration": (None, None),
        "bee_nest_destroyed": (None, None),
        "bred_animals": (None, None),
        "brewed_potion": (None, None),
        "changed_dimension": (None, None),
        "channeled_lightning": (None, None),
        "construct_beacon": (None, None),
        "consume_item": (None, None),
        "crafter_recipe_crafted": ("1.20.5", None),
        "cured_zombie_villager": (None, None),
        "default_block_use": ("1.20.5", None),
        "effects_changed": (None, None),
        "enchanted_item": (None, None),
        "enter_block": (None, None),
        "entity_hurt_player": (None, None),
        "entity_killed_player": (None, None),
        "fall_after_explosion": ("1.20.5", None),
        "fall_from_height": (None, None),
        "filled_bucket": (None, None),
        "fishing_rod_hooked": (None, None),
        "hero_of_the_village": (None, None),
        "impossible": (None, None),
        "inventory_changed": (None, None),
        "item_durability_changed": (None, None),
        "item_used_on_block": (None, None),
        "kill_mob_near_sculk_catalyst": (None, None),
        "killed_by_arrow": ("1.21.2", None),
        "killed_by_crossbow": (None, "1.21.2"),
        "levitation": (None, None),
        "lightning_strike": (None, None),
        "location": (None, None),
        "nether_travel": (None, None),
        "placed_block": (None, None),
        "player_generates_container_loot": (None, None),
        "player_hurt_entity": (None, None),
        "player_interacted_with_entity": (None, None),
        "player_killed_entity": (None, None),
        "player_sheared_equipment": ("1.21.6", None),
        "recipe_crafted": (None, None),
        "recipe_unlocked": (None, None),
        "ride_entity_in_lava": (None, None),
        "shot_crossbow": (None, None),
        "slept_in_bed": (None, None),
        "slide_down_block": (None, None),
        "spear_mobs": ("1.21.11", None),
        "started_riding": (None, None),
        "summoned_entity": (None, None),
        "tame_animal": (None, None),
        "target_hit": (None, None),
        "thrown_item_picked_up_by_entity": (None, None),
        "thrown_item_picked_up_by_player": (None, None),
        "tick": (None, None),
        "used_ender_eye": (None, None),
        "used_totem": (None, None),
        "using_item": (None, None),
        "villager_trade": (None, None),
        "voluntary_exile": (None, None),
    },
}
